In [16]:
import pandas as pd
web_series=pd.read_excel('web_series.xlsx')

In [17]:
len(web_series)

4560

In [18]:
for i in range(0,4560):
    temp=str(str(web_series.iloc[i]['url']).split())
    web_series.iloc[i]['url']=temp.replace("/title/","").replace("/?ref_=adv_li_tt","")

In [19]:
web_series.isnull().sum()

title             0
url               0
genre          1405
description       0
crew             21
dtype: int64

In [20]:
web_series=web_series.dropna()

In [21]:
web_series=web_series.reset_index()

In [22]:
web_series.drop(web_series.columns[web_series.columns.str.contains('index',case = False)],axis = 1, inplace = True)

In [24]:
web_series

,title,url,genre,description,crew
0,The Last of Us,['tt3581920'],"Action, Adventure, Drama","After a global pandemic destroys civilization,...","Stars: Pedro Pascal, Bella Ramsey, Gabriel Lun..."
1,Poker Face,['tt14269590'],"Crime, Drama, Mystery",Charlie has an extraordinary ability to determ...,"Stars: Natasha Lyonne, Benjamin Bratt, Robert ..."
2,Shrinking,['tt15677150'],"Comedy, Drama",A grieving therapist starts to tell his client...,"Stars: Jason Segel, Jessica Williams, Harrison..."
3,Lockwood & Co,['tt13802576'],"Action, Adventure, Drama","A tiny startup, run by two teenage boys and a ...","Stars: Ruby Stokes, Cameron Chapman, Ali Hadji..."
4,That '90s Show,['tt15591076'],"Comedy, Drama, Romance","Now it's 1995, Leia Forman is visiting her gra...","Stars: Kurtwood Smith, Debra Jo Rupp, Callie H..."
...,...,...,...,...,...
3141,Content Cop,['tt6111552'],"Comedy, Crime, Talk-Show",In an effort to bring justice to the YouTube c...,"Stars: Ian Washburn, Calvin Vail, Bryan Le, Ro..."
3142,Highston,['tt4630676'],Comedy,A young man becomes immersed in a world of his...,"Stars: Chris Parnell, Mary Lynn Rajskub, Curti..."
3143,Suryaputra Karn,['tt5328326'],Fantasy,"Karna, son of Surya and Kunti and the doyen of...","Stars: Farnaz Shetty, Gautam Rode, Aishwarya S..."
3144,Kerchi: Dakarguli Gmirebi,['tt5289208'],"Drama, War",Story of ethnic Georgians fighting in the Red ...,"Stars: Giorgi Makharadze, Giorgi Tsaava, Revaz..."
3145,The Nightly Show with Larry Wilmore,['tt3722332'],"Comedy, News, Talk-Show",A late night satirical talk show hosted by Lar...,"Stars: Larry Wilmore, Mike Yard, Rory Albanese..."

In [25]:
web_series['actors']=web_series['crew']

In [26]:
web_series=web_series.drop(columns=['crew'])

In [27]:
web_series.head(2)

,title,url,genre,description,actors
0,The Last of Us,['tt3581920'],"Action, Adventure, Drama","After a global pandemic destroys civilization,...","Stars: Pedro Pascal, Bella Ramsey, Gabriel Lun..."
1,Poker Face,['tt14269590'],"Crime, Drama, Mystery",Charlie has an extraordinary ability to determ...,"Stars: Natasha Lyonne, Benjamin Bratt, Robert ..."

In [28]:
len(web_series)

3146

In [29]:
# For Actors
for i in range(0,3146):
    temp=str(web_series.iloc[i]['actors']).split("Stars: ")
    try:
        web_series.iloc[i]['actors']=temp[1]
    except IndexError:
        web_series.iloc[i]['actors']='NA'

In [30]:
web_series.head(2)

,title,url,genre,description,actors
0,The Last of Us,['tt3581920'],"Action, Adventure, Drama","After a global pandemic destroys civilization,...","Pedro Pascal, Bella Ramsey, Gabriel Luna, Anna..."
1,Poker Face,['tt14269590'],"Crime, Drama, Mystery",Charlie has an extraordinary ability to determ...,"Natasha Lyonne, Benjamin Bratt, Robert Loftus,..."

In [31]:
web_series.isnull().sum()

title          0
url            0
genre          0
description    0
actors         0
dtype: int64

In [32]:
# Splitting Genre
for i in range(0,3146):
    temp=str(web_series.iloc[i]['genre']).replace(",","")
    l=temp.split()
    try:
        web_series.iloc[i]['genre']=l
    except Exception as e:
        web_series.iloc[i]['genre']='NA'

In [33]:
web_series.head(2)

,title,url,genre,description,actors
0,The Last of Us,['tt3581920'],"[Action, Adventure, Drama]","After a global pandemic destroys civilization,...","Pedro Pascal, Bella Ramsey, Gabriel Luna, Anna..."
1,Poker Face,['tt14269590'],"[Crime, Drama, Mystery]",Charlie has an extraordinary ability to determ...,"Natasha Lyonne, Benjamin Bratt, Robert Loftus,..."

In [34]:
# Splitting Actors
for i in range(0,3146):
    temp=web_series.iloc[i]['actors']
    l=temp.split(",")
    try:
        web_series.iloc[i]['actors']=l
    except Exception as e:
        web_series.iloc[i]['actors']='NA'

In [35]:
web_series.head(2)

,title,url,genre,description,actors
0,The Last of Us,['tt3581920'],"[Action, Adventure, Drama]","After a global pandemic destroys civilization,...","[Pedro Pascal, Bella Ramsey, Gabriel Luna, ..."
1,Poker Face,['tt14269590'],"[Crime, Drama, Mystery]",Charlie has an extraordinary ability to determ...,"[Natasha Lyonne, Benjamin Bratt, Robert Loft..."

In [36]:
# Fixing url
for i in range(0,3146):
    web_series.iloc[i]['url']=web_series.iloc[i]['url'].replace("'","").replace("[","").replace("]","")

In [37]:
# Exporting web series
import pickle
pickle.dump(web_series.to_dict(), open('web_series.pkl','wb'))

In [38]:
# Deleting Space
for i in range(0,3146):  
    for j in range(0,len(web_series.iloc[i]['actors'])):
        web_series.iloc[i]['actors'][j]=web_series.iloc[i]['actors'][j].replace(" ","")

In [39]:
web_series.head(4)

,title,url,genre,description,actors
0,The Last of Us,tt3581920,"[Action, Adventure, Drama]","After a global pandemic destroys civilization,...","[PedroPascal, BellaRamsey, GabrielLuna, AnnaTorv]"
1,Poker Face,tt14269590,"[Crime, Drama, Mystery]",Charlie has an extraordinary ability to determ...,"[NatashaLyonne, BenjaminBratt, RobertLoftus, S..."
2,Shrinking,tt15677150,"[Comedy, Drama]",A grieving therapist starts to tell his client...,"[JasonSegel, JessicaWilliams, HarrisonFord, Lu..."
3,Lockwood & Co,tt13802576,"[Action, Adventure, Drama]","A tiny startup, run by two teenage boys and a ...","[RubyStokes, CameronChapman, AliHadji-Heshmati..."

In [40]:
# Splitting Web Series's Descriptions
web_series['description']=web_series['description'].apply(lambda x:x.split())

In [41]:
# Creating new column 'tags'
web_series['tags'] =web_series['genre']  + web_series['actors'] + web_series['description']

In [42]:
# Dropping none required columns
web_series=web_series.drop(columns=['genre','description','actors'])

In [43]:
# Combining tags
web_series['tags'] = web_series['tags'].apply(lambda x:" ".join(x))

In [44]:
# Making tags lowercase
web_series['tags']= web_series['tags'].apply(lambda x:x.lower())

In [45]:
web_series['tags'].head(4)

0    action adventure drama pedropascal bellaramsey...
1    crime drama mystery natashalyonne benjaminbrat...
2    comedy drama jasonsegel jessicawilliams harris...
3    action adventure drama rubystokes cameronchapm...
Name: tags, dtype: object

In [46]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [48]:
def stemming(text):
    List=[]
    for i in text.split():
        List.append(ps.stem(i))
    return " ".join(List)

In [49]:
web_series['tags']= web_series['tags'].apply(stemming)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3200, stop_words='english')
vectors=cv.fit_transform(web_series['tags']).toarray()

In [51]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0),
 (2838, 0.3241018617760822),
 (37, 0.3131121455425747),
 (1970, 0.3131121455425747),
 (1828, 0.3067859955389482),
 (2414, 0.3067859955389482),
 (2887, 0.3067859955389482),
 (1320, 0.29411764705882354),
 (1625, 0.29250896965085227),
 (2415, 0.28301965507089),
 (760, 0.2782074420373286),
 (1832, 0.269069117598525),
 (2925, 0.25928148942086576),
 (1539, 0.25854384499750954),
 (293, 0.25724787771376323),
 (1579, 0.25724787771376323),
 (1512, 0.25048971643405976),
 (2182, 0.24253562503633297),
 (2328, 0.24253562503633297),
 (1418, 0.24253562503633294),
 (2233, 0.24253562503633294),
 (570, 0.23529411764705882),
 (2386, 0.23529411764705882),
 (1068, 0.23008949665421113),
 (1795, 0.23008949665421113),
 (3, 0.2286647801900118),
 (1515, 0.2286647801900118),
 (2941, 0.2286647801900118),
 (1694, 0.22518867455552247),
 (2985, 0.22256595362986287),
 (1787, 0.2193817272381392),
 (1877, 0.2193817272381392),
 (2111, 0.2193817272381392),
 (2940, 0.2193817272381392),
 (7, 0.21693045781865616),
 (291, 0.21693045781865616),
 (34, 0.21170244960998527),
 (526, 0.2100420126042015),
 (720, 0.2100420126042015),
 (1330, 0.2100420126042015),
 (1517, 0.2100420126042015),
 (2215, 0.2100420126042015),
 (2232, 0.2100420126042015),
 (2230, 0.20683507599800766),
 (518, 0.20683507599800763),
 (1449, 0.20683507599800763),
 (2322, 0.20683507599800763),
 (287, 0.20228869496966945),
 (578, 0.20228869496966945),
 (2817, 0.20228869496966945),
 (186, 0.20180183819889375),
 (513, 0.20180183819889375),
 (530, 0.20180183819889375),
 (1281, 0.20180183819889375),
 (1342, 0.20180183819889375),
 (1895, 0.20180183819889375),
 (2211, 0.20180183819889375),
 (2563, 0.20180183819889375),
 (2694, 0.20180183819889375),
 (3009, 0.20180183819889375),
 (3055, 0.20180183819889375),
 (606, 0.19802950859533489),
 (892, 0.19802950859533489),
 (2874, 0.19802950859533489),
 (179, 0.19446111706564934),
 (511, 0.19446111706564934),
 (1326, 0.19446111706564934),
 (1474, 0.19446111706564934),
 (1777, 0.19446111706564934),
 (1783, 0.19446111706564934),
 (1874, 0.19446111706564934),
 (2219, 0.19446111706564934),
 (3034, 0.19446111706564934),
 (126, 0.19402850002906638),
 (2908, 0.19402850002906638),
 (1383, 0.19026059766179765),
 (2330, 0.19026059766179765),
 (2736, 0.19026059766179765),
 (112, 0.1878672873255448),
 (256, 0.1878672873255448),
 (335, 0.1878672873255448),
 (502, 0.1878672873255448),
 (593, 0.1878672873255448),
 (1216, 0.1878672873255448),
 (2048, 0.1878672873255448),
 (2147, 0.1878672873255448),
 (2180, 0.1878672873255448),
 (2538, 0.1878672873255448),
 (2790, 0.1878672873255448),
 (2943, 0.1878672873255448),
 (2360, 0.18670401120373464),
 (1061, 0.1849316803638273),
 (1056, 0.18333969940564224),
 (2251, 0.18333969940564224),
 (2396, 0.18333969940564224),
 (2657, 0.18333969940564224),
 (722, 0.18281810603178267),
 (51, 0.18190171877724973),
 (130, 0.18190171877724973),
 (345, 0.18190171877724973),
 (916, 0.18190171877724973),
 (938, 0.18190171877724973),
 (1329, 0.18190171877724973),
 (1984, 0.18190171877724973),
 (2387, 0.18190171877724973),
 (2543, 0.18190171877724973),
 (2704, 0.18190171877724973),
 (2913, 0.18190171877724973),
 (3100, 0.18190171877724973),
 (36, 0.1764705882352941),
 (497, 0.1764705882352941),
 (736, 0.1764705882352941),
 (831, 0.1764705882352941),
 (1284, 0.1764705882352941),
 (1423, 0.1764705882352941),
 (1894, 0.1764705882352941),
 (2112, 0.1764705882352941),
 (2708, 0.1764705882352941),
 (1141, 0.17424273674761284),
 (1560, 0.17424273674761284),
 (2326, 0.17424273674761284),
 (58, 0.17149858514250885),
 (94, 0.17149858514250885),
 (368, 0.17149858514250885),
 (577, 0.17149858514250885),
 (950, 0.17149858514250885),
 (1010, 0.17149858514250885),
 (1045, 0.17149858514250885),
 (1376, 0.17149858514250885),
 (1672, 0.17149858514250885),
 (1747, 0.17149858514250885),
 (1940, 0.17149858514250885),
 (2090, 0.17149858514250885),
 (2489, 0.17149858514250885),
 (2523, 0.17149858514250885),
 (2897, 0.17149858514250885),
 (3053, 0.17149858514250885),
 (643, 0.17149858514250882),
 (701, 0.17149858514250882),
 (1231, 0.17149858514250882),
 (1778, 0.17149858514250882),
 (1916, 0.17149858514250882),
 (1921, 0.17149858514250882),
 (1933, 0.17149858514250882),
 (2044, 0.17149858514250882),
 (2206, 0.17149858514250882),
 (2213, 0.17149858514250882),
 (2262, 0.17149858514250882),
 (2544, 0.17149858514250882),
 (2580, 0.17149858514250882),
 (2683, 0.17149858514250882),
 (550, 0.16692446522239715),
 (874, 0.16692446522239715),
 (966, 0.16692446522239715),
 (2380, 0.16692446522239715),
 (2471, 0.16692446522239715),
 (2504, 0.16692446522239715),
 (2528, 0.16692446522239715),
 (2904, 0.16692446522239715),
 (2987, 0.16692446522239715),
 (623, 0.16269784336399212),
 (943, 0.16269784336399212),
 (1016, 0.16269784336399212),
 (1098, 0.16269784336399212),
 (1175, 0.16269784336399212),
 (1202, 0.16269784336399212),
 (1378, 0.16269784336399212),
 (1809, 0.16269784336399212),
 (1937, 0.16269784336399212),
 (2529, 0.16269784336399212),
 (2598, 0.16269784336399212),
 (2993, 0.16269784336399212),
 (3097, 0.16269784336399212),
 (3126, 0.16269784336399212),
 (352, 0.16169041669088863),
 (747, 0.16169041669088863),
 (903, 0.16169041669088863),
 (1191, 0.16169041669088863),
 (1509, 0.16169041669088863),
 (1524, 0.16169041669088863),
 (1833, 0.16169041669088863),
 (2587, 0.16169041669088863),
 (902, 0.15877683720748895),
 (917, 0.15877683720748895),
 (1077, 0.15877683720748895),
 (1244, 0.15877683720748895),
 (1468, 0.15877683720748895),
 (1469, 0.15877683720748895),
 (1657, 0.15877683720748895),
 (1708, 0.15877683720748895),
 (1713, 0.15877683720748895),
 (2574, 0.15877683720748895),
 (3017, 0.15877683720748895),
 (1542, 0.15534712747612348),
 (135, 0.15512630699850571),
 (520, 0.15512630699850571),
 (1558, 0.15512630699850571),
 (1699, 0.15512630699850571),
 (1888, 0.15512630699850571),
 (2124, 0.15512630699850571),
 (2914, 0.15512630699850571),
 (56, 0.1533929977694741),
 (528, 0.1533929977694741),
 (651, 0.1533929977694741),
 (924, 0.1533929977694741),
 (970, 0.1533929977694741),
 (999, 0.1533929977694741),
 (1024, 0.1533929977694741),
 (1772, 0.1533929977694741),
 (1911, 0.1533929977694741),
 (2257, 0.1533929977694741),
 (2356, 0.1533929977694741),
 (2540, 0.1533929977694741),
 (2558, 0.1533929977694741),
 (2674, 0.1533929977694741),
 (2727, 0.1533929977694741),
 (2789, 0.1533929977694741),
 (2815, 0.1533929977694741),
 (2891, 0.1533929977694741),
 (2967, 0.1533929977694741),
 (3022, 0.1533929977694741),
 (3044, 0.1533929977694741),
 (41, 0.1517165212272521),
 (704, 0.1517165212272521),
 (766, 0.1517165212272521),
 (1581, 0.1517165212272521),
 (2208, 0.1517165212272521),
 (2645, 0.1517165212272521),
 (354, 0.14852213144650117),
 (448, 0.14852213144650117),
 (534, 0.14852213144650117),
 (846, 0.14852213144650117),
 (1421, 0.14852213144650117),
 (2198, 0.14852213144650117),
 (2216, 0.14852213144650117),
 (2569, 0.14852213144650117),
 (2631, 0.14852213144650117),
 (3070, 0.14852213144650117),
 (8, 0.14625448482542613),
 (304, 0.14625448482542613),
 (453, 0.14625448482542613),
 (539, 0.14625448482542613),
 (574, 0.14625448482542613),
 (676, 0.14625448482542613),
 (688, 0.14625448482542613),
 (919, 0.14625448482542613),
 (934, 0.14625448482542613),
 (944, 0.14625448482542613),
 (1006, 0.14625448482542613),
 (1105, 0.14625448482542613),
 (1290, 0.14625448482542613),
 (1302, 0.14625448482542613),
 (1445, 0.14625448482542613),
 (1486, 0.14625448482542613),
 (1686, 0.14625448482542613),
 (1830, 0.14625448482542613),
 (1855, 0.14625448482542613),
 (2336, 0.14625448482542613),
 (2391, 0.14625448482542613),
 (2537, 0.14625448482542613),
 (2666, 0.14625448482542613),
 (2703, 0.14625448482542613),
 (2919, 0.14625448482542613),
 (2924, 0.14625448482542613),
 (3050, 0.14625448482542613),
 (3092, 0.14625448482542613),
 (429, 0.1455213750217998),
 (890, 0.1455213750217998),
 (2011, 0.1455213750217998),
 (2642, 0.1455213750217998),
 (2953, 0.1455213750217998),
 (782, 0.14269544824634822),
 (941, 0.14269544824634822),
 (1841, 0.14269544824634822),
 (1936, 0.14269544824634822),
 (2159, 0.14269544824634822),
 (2362, 0.14269544824634822),
 (2575, 0.14269544824634822),
 (3007, 0.14269544824634822),
 (19, 0.140028008402801),
 (57, 0.140028008402801),
 (276, 0.140028008402801),
 (312, 0.140028008402801),
 (318, 0.140028008402801),
 (399, 0.140028008402801),
 (535, 0.140028008402801),
 (566, 0.140028008402801),
 (785, 0.140028008402801),
 (1221, 0.140028008402801),
 (1263, 0.140028008402801),
 (1296, 0.140028008402801),
 (1340, 0.140028008402801),
 (1341, 0.140028008402801),
 (1355, 0.140028008402801),
 (1356, 0.140028008402801),
 (1513, 0.140028008402801),
 (1627, 0.140028008402801),
 (1693, 0.140028008402801),
 (1776, 0.140028008402801),
 (1814, 0.140028008402801),
 (1839, 0.140028008402801),
 (1900, 0.140028008402801),
 (1917, 0.140028008402801),
 (2103, 0.140028008402801),
 (2199, 0.140028008402801),
 (2204, 0.140028008402801),
 (2430, 0.140028008402801),
 (2455, 0.140028008402801),
 (2467, 0.140028008402801),
 (2500, 0.140028008402801),
 (2615, 0.140028008402801),
 (2648, 0.140028008402801),
 (2678, 0.140028008402801),
 (2845, 0.140028008402801),
 (3032, 0.140028008402801),
 (3086, 0.140028008402801),
 (3125, 0.140028008402801),
 (545, 0.13750477455423168),
 (1626, 0.13750477455423168),
 (2482, 0.13750477455423168),
 (2584, 0.13750477455423168),
 (74, 0.13511320473331348),
 (517, 0.13511320473331348),
 (1265, 0.13511320473331348),
 (14, 0.1345345587992625),
 (26, 0.1345345587992625),
 (45, 0.1345345587992625),
 (61, 0.1345345587992625),
 (224, 0.1345345587992625),
 (259, 0.1345345587992625),
 (338, 0.1345345587992625),
 (342, 0.1345345587992625),
 (355, 0.1345345587992625),
 (510, 0.1345345587992625),
 (537, 0.1345345587992625),
 (538, 0.1345345587992625),
 (590, 0.1345345587992625),
 (637, 0.1345345587992625),
 (677, 0.1345345587992625),
 (933, 0.1345345587992625),
 (1112, 0.1345345587992625),
 (1359, 0.1345345587992625),
 (1362, 0.1345345587992625),
 (1570, 0.1345345587992625),
 (1584, 0.1345345587992625),
 (1805, 0.1345345587992625),
 (1811, 0.1345345587992625),
 (1891, 0.1345345587992625),
 (1897, 0.1345345587992625),
 (1994, 0.1345345587992625),
 (2158, 0.1345345587992625),
 (2197, 0.1345345587992625),
 (2217, 0.1345345587992625),
 (2333, 0.1345345587992625),
 (2365, 0.1345345587992625),
 (2873, 0.1345345587992625),
 (2965, 0.1345345587992625),
 (3020, 0.1345345587992625),
 (3054, 0.1345345587992625),
 (92, 0.13068205256070964),
 (733, 0.13068205256070964),
 (1115, 0.13068205256070964),
 (49, 0.12964074471043288),
 (60, 0.12964074471043288),
 (76, 0.12964074471043288),
 (90, 0.12964074471043288),
 (123, 0.12964074471043288),
 (134, 0.12964074471043288),
 (146, 0.12964074471043288),
 (151, 0.12964074471043288),
 (189, 0.12964074471043288),
 (190, 0.12964074471043288),
 (326, 0.12964074471043288),
 (346, 0.12964074471043288),
 (349, 0.12964074471043288),
 (463, 0.12964074471043288),
 (508, 0.12964074471043288),
 (548, 0.12964074471043288),
 (609, 0.12964074471043288),
 (625, 0.12964074471043288),
 (757, 0.12964074471043288),
 (841, 0.12964074471043288),
 (1071, 0.12964074471043288),
 (1074, 0.12964074471043288),
 (1076, 0.12964074471043288),
 (1102, 0.12964074471043288),
 (1104, 0.12964074471043288),
 (1129, 0.12964074471043288),
 (1179, 0.12964074471043288),
 (1406, 0.12964074471043288),
 (1407, 0.12964074471043288),
 (1431, 0.12964074471043288),
 (1435, 0.12964074471043288),
 (1444, 0.12964074471043288),
 (1595, 0.12964074471043288),
 (1637, 0.12964074471043288),
 (1651, 0.12964074471043288),
 (1669, 0.12964074471043288),
 (1775, 0.12964074471043288),
 (1785, 0.12964074471043288),
 (1851, 0.12964074471043288),
 (1955, 0.12964074471043288),
 (2069, 0.12964074471043288),
 (2071, 0.12964074471043288),
 (2263, 0.12964074471043288),
 (2275, 0.12964074471043288),
 (2289, 0.12964074471043288),
 (2439, 0.12964074471043288),
 (2700, 0.12964074471043288),
 (2726, 0.12964074471043288),
 (2826, 0.12964074471043288),
 (2882, 0.12964074471043288),
 (2885, 0.12964074471043288),
 (3004, 0.12964074471043288),
 (3059, 0.12964074471043288),
 (3116, 0.12964074471043288),
 (770, 0.12666009927622474),
 (59, 0.12524485821702988),
 (178, 0.12524485821702988),
 (203, 0.12524485821702988),
 (277, 0.12524485821702988),
 (541, 0.12524485821702988),
 (565, 0.12524485821702988),
 (685, 0.12524485821702988),
 (700, 0.12524485821702988),
 (801, 0.12524485821702988),
 (1095, 0.12524485821702988),
 (1103, 0.12524485821702988),
 (1114, 0.12524485821702988),
 (1122, 0.12524485821702988),
 (1186, 0.12524485821702988),
 (1235, 0.12524485821702988),
 (1396, 0.12524485821702988),
 (1461, 0.12524485821702988),
 (1629, 0.12524485821702988),
 (1784, 0.12524485821702988),
 (1960, 0.12524485821702988),
 (1995, 0.12524485821702988),
 (2179, 0.12524485821702988),
 (2201, 0.12524485821702988),
 (2229, 0.12524485821702988),
 (2237, 0.12524485821702988),
 (2311, 0.12524485821702988),
 (2349, 0.12524485821702988),
 (2366, 0.12524485821702988),
 (2512, 0.12524485821702988),
 (2559, 0.12524485821702988),
 (2612, 0.12524485821702988),
 (2620, 0.12524485821702988),
 (2876, 0.12524485821702988),
 (2902, 0.12524485821702988),
 (2930, 0.12524485821702988),
 (3074, 0.12524485821702988),
 (3085, 0.12524485821702988),
 (6, 0.12126781251816648),
 (40, 0.12126781251816648),
 (67, 0.12126781251816648),
 (68, 0.12126781251816648),
 (193, 0.12126781251816648),
 (232, 0.12126781251816648),
 (325, 0.12126781251816648),
 (376, 0.12126781251816648),
 (509, 0.12126781251816648),
 (543, 0.12126781251816648),
 (564, 0.12126781251816648),
 (586, 0.12126781251816648),
 (608, 0.12126781251816648),
 (695, 0.12126781251816648),
 (708, 0.12126781251816648),
 (725, 0.12126781251816648),
 (974, 0.12126781251816648),
 (1052, 0.12126781251816648),
 (1223, 0.12126781251816648),
 (1427, 0.12126781251816648),
 (1495, 0.12126781251816648),
 (1550, 0.12126781251816648),
 (1555, 0.12126781251816648),
 (1692, 0.12126781251816648),
 (1800, 0.12126781251816648),
 (1807, 0.12126781251816648),
 (1821, 0.12126781251816648),
 (1849, 0.12126781251816648),
 (1856, 0.12126781251816648),
 (1899, 0.12126781251816648),
 (1945, 0.12126781251816648),
 (2010, 0.12126781251816648),
 (2062, 0.12126781251816648),
 (2070, 0.12126781251816648),
 (2181, 0.12126781251816648),
 (2218, 0.12126781251816648),
 (2254, 0.12126781251816648),
 (2300, 0.12126781251816648),
 (2411, 0.12126781251816648),
 (2431, 0.12126781251816648),
 (2445, 0.12126781251816648),
 (2524, 0.12126781251816648),
 (2533, 0.12126781251816648),
 (2550, 0.12126781251816648),
 (2552, 0.12126781251816648),
 (2670, 0.12126781251816648),
 (2689, 0.12126781251816648),
 (2701, 0.12126781251816648),
 (3075, 0.12126781251816648),
 (3117, 0.12126781251816648),
 (3122, 0.12126781251816648),
 (521, 0.11961783342433499),
 (2369, 0.11961783342433499),
 (2801, 0.11803342130469505),
 (25, 0.11764705882352941),
 (63, 0.11764705882352941),
 (64, 0.11764705882352941),
 (161, 0.11764705882352941),
 (196, 0.11764705882352941),
 (324, 0.11764705882352941),
 (419, 0.11764705882352941),
 (447, 0.11764705882352941),
 (454, 0.11764705882352941),
 (529, 0.11764705882352941),
 (626, 0.11764705882352941),
 (634, 0.11764705882352941),
 (660, 0.11764705882352941),
 (702, 0.11764705882352941),
 (749, 0.11764705882352941),
 (781, 0.11764705882352941),
 (818, 0.11764705882352941),
 (826, 0.11764705882352941),
 (875, 0.11764705882352941),
 (915, 0.11764705882352941),
 (983, 0.11764705882352941),
 (996, 0.11764705882352941),
 (1019, 0.11764705882352941),
 (1117, 0.11764705882352941),
 (1261, 0.11764705882352941),
 (1344, 0.11764705882352941),
 (1366, 0.11764705882352941),
 (1370, 0.11764705882352941),
 (1408, 0.11764705882352941),
 (1463, 0.11764705882352941),
 (1494, 0.11764705882352941),
 (1671, 0.11764705882352941),
 (1738, 0.11764705882352941),
 (1844, 0.11764705882352941),
 (1853, 0.11764705882352941),
 (1884, 0.11764705882352941),
 (1958, 0.11764705882352941),
 (2001, 0.11764705882352941),
 (2622, 0.11764705882352941),
 (2741, 0.11764705882352941),
 (2746, 0.11764705882352941),
 (2816, 0.11764705882352941),
 (2909, 0.11764705882352941),
 (2929, 0.11764705882352941),
 (2955, 0.11764705882352941),
 (2957, 0.11764705882352941),
 (2962, 0.11764705882352941),
 (2995, 0.11764705882352941),
 (3112, 0.11764705882352941),
 (24, 0.1143323900950059),
 (42, 0.1143323900950059),
 (50, 0.1143323900950059),
 (88, 0.1143323900950059),
 (138, 0.1143323900950059),
 (219, 0.1143323900950059),
 (281, 0.1143323900950059),
 (437, 0.1143323900950059),
 (461, 0.1143323900950059),
 (603, 0.1143323900950059),
 (627, 0.1143323900950059),
 (715, 0.1143323900950059),
 (748, 0.1143323900950059),
 (963, 0.1143323900950059),
 (1050, 0.1143323900950059),
 (1151, 0.1143323900950059),
 (1260, 0.1143323900950059),
 (1274, 0.1143323900950059),
 (1405, 0.1143323900950059),
 (1440, 0.1143323900950059),
 (1473, 0.1143323900950059),
 (1481, 0.1143323900950059),
 (1592, 0.1143323900950059),
 (1597, 0.1143323900950059),
 (1684, 0.1143323900950059),
 (1802, 0.1143323900950059),
 (1826, 0.1143323900950059),
 (1834, 0.1143323900950059),
 (1842, 0.1143323900950059),
 (1852, 0.1143323900950059),
 (1878, 0.1143323900950059),
 (1881, 0.1143323900950059),
 (2029, 0.1143323900950059),
 (2083, 0.1143323900950059),
 (2178, 0.1143323900950059),
 (2194, 0.1143323900950059),
 (2393, 0.1143323900950059),
 (2470, 0.1143323900950059),
 (2496, 0.1143323900950059),
 (2549, 0.1143323900950059),
 (2719, 0.1143323900950059),
 (2722, 0.1143323900950059),
 (2772, 0.1143323900950059),
 (2932, 0.1143323900950059),
 (3105, 0.1143323900950059),
 (3133, 0.1143323900950059),
 (73, 0.11128297681493143),
 (84, 0.11128297681493143),
 (207, 0.11128297681493143),
 (303, 0.11128297681493143),
 (336, 0.11128297681493143),
 (501, 0.11128297681493143),
 (569, 0.11128297681493143),
 (585, 0.11128297681493143),
 (595, 0.11128297681493143),
 (662, 0.11128297681493143),
 (678, 0.11128297681493143),
 (703, 0.11128297681493143),
 (731, 0.11128297681493143),
 (808, 0.11128297681493143),
 (899, 0.11128297681493143),
 (994, 0.11128297681493143),
 (1064, 0.11128297681493143),
 (1065, 0.11128297681493143),
 (1084, 0.11128297681493143),
 (1090, 0.11128297681493143),
 (1234, 0.11128297681493143),
 (1654, 0.11128297681493143),
 (1677, 0.11128297681493143),
 (1861, 0.11128297681493143),
 (1862, 0.11128297681493143),
 (1964, 0.11128297681493143),
 (1999, 0.11128297681493143),
 (2107, 0.11128297681493143),
 (2177, 0.11128297681493143),
 (2316, 0.11128297681493143),
 (2401, 0.11128297681493143),
 (2568, 0.11128297681493143),
 (2608, 0.11128297681493143),
 (2610, 0.11128297681493143),
 (2650, 0.11128297681493143),
 (2672, 0.11128297681493143),
 (2742, 0.11128297681493143),
 (2763, 0.11128297681493143),
 (2829, 0.11128297681493143),
 (2850, 0.11128297681493143),
 (2875, 0.11128297681493143),
 (2950, 0.11128297681493143),
 (3039, 0.11128297681493143),
 (3068, 0.11128297681493143),
 (10, 0.10846522890932808),
 (66, 0.10846522890932808),
 (97, 0.10846522890932808),
 (113, 0.10846522890932808),
 (242, 0.10846522890932808),
 (261, 0.10846522890932808),
 (284, 0.10846522890932808),
 (299, 0.10846522890932808),
 (589, 0.10846522890932808),
 (650, 0.10846522890932808),
 (673, 0.10846522890932808),
 (682, 0.10846522890932808),
 (844, 0.10846522890932808),
 (852, 0.10846522890932808),
 (869, 0.10846522890932808),
 (918, 0.10846522890932808),
 (954, 0.10846522890932808),
 (1041, 0.10846522890932808),
 (1135, 0.10846522890932808),
 (1159, 0.10846522890932808),
 (1198, 0.10846522890932808),
 (1293, 0.10846522890932808),
 (1315, 0.10846522890932808),
 (1357, 0.10846522890932808),
 (1635, 0.10846522890932808),
 (1659, 0.10846522890932808),
 (1728, 0.10846522890932808),
 (1751, 0.10846522890932808),
 (1768, 0.10846522890932808),
 (1796, 0.10846522890932808),
 (1815, 0.10846522890932808),
 (1827, 0.10846522890932808),
 (1829, 0.10846522890932808),
 (1845, 0.10846522890932808),
 (1914, 0.10846522890932808),
 (1977, 0.10846522890932808),
 (2076, 0.10846522890932808),

In [52]:
def recommend(web_show):
    index=web_series[web_series['title']==web_show].index[0]
    distance=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x:x[1])
    for i in distance[1:10]:
        print(web_series.iloc[i[0]].title)

In [53]:
recommend("My Mister")

Parizaad
Encounter
Tell Me Lies
Kehne Ko Humsafar Hain
The Glory
Neumatt
Catherine the Great
Special
Citrus

In [54]:
import pickle
pickle.dump(web_series,open('web_series_last.pkl','wb'))
pickle.dump(similarity,open('web_series_similarity.pkl','wb'))
pickle.dump(vectors, open('vectors.pkl','wb'))

In [55]:
vectors.shape

(3146, 3200)

In [56]:
import sqlite3
import sqlalchemy

In [57]:
engine = sqlalchemy.create_engine('sqlite:///web_series.sqlite')

In [58]:
web_series = pickle.load(open('web_series.pkl', 'rb'))

In [59]:
web_series = pd.DataFrame(web_series)

In [60]:
web_series['genre'] = web_series['genre'].apply(lambda x: "$".join(x))

In [61]:
web_series['actors'] = web_series['actors'].apply(lambda x: "$".join(x))

In [62]:
web_series.head(2)

,title,url,genre,description,actors
0,The Last of Us,tt3581920,Action$Adventure$Drama,"After a global pandemic destroys civilization,...",Pedro Pascal$ Bella Ramsey$ Gabriel Luna$ Anna...
1,Poker Face,tt14269590,Crime$Drama$Mystery,Charlie has an extraordinary ability to determ...,Natasha Lyonne$ Benjamin Bratt$ Robert Loftus$...

In [63]:
web_series = web_series.applymap(str)

In [64]:
web_series.to_sql('web_series', engine)